### ISSUE TITLE
Commands using "--format json" return malformed JSON

### ISSUE THREAD

**Issue by davidstevenrose** [Files-com/files-cli#2]
When I use a list command such as ``` users list ``` with the ``` --format json ``` parameter, I receive a JSON array that is missing the closing right square bracket.

For example, by running the command
``` 
files-cli.exe users list --search "TEST" --fields "id,username" --format json --api-key <My-API-Key> --ignore-version-check 
```
I get the following similar response:
``` 
[{    
    "id": 000001,    
    "username": "a-TEST"
 },
 {    
    "id": 000002,   
    "username": "b-TEST"
 } 
```
The right square bracket is missing at the end.

I am using files-cli_Windows_64bit version on Windows. I tested this on release v2.0.6

**Comment by Files-Michael** [comment]
Thank you for taking the time to file this issue.

For the quickest investigation into this issue, please send an authenticated support ticket through the Files.com web interface. You can submit a support request using the Contact Support option in the top-right menu of the web interface. You access the menu by clicking on your user name.
